[package]
name = "httpie"
version = "0.1.0"
authors = ["fnlcon <fnlcon@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.4"
